image: 
  file: .gitpod.Dockerfile

tasks:
  # - init: /usr/bin/start-vnc-session.sh
  - command: zsh

# Ports to expose on workspace startup
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python@2020.10.332292344:5ctthQ25Qni5/aAuOIUTYQ==
    