name: Raindrop-Removal-With-Light-Field-Image-Using-Image-Inpainting
channels:
  - intel
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - scipy=1.2.1
  - opencv
  - torchvision
  - pyaml
  - scikit-image=0.17.1
  - jupyterlab
  - pillow
  - pylint
  - tensorflow=1.15.2
  - glog
  - easydict
  - matplotlib
