name: Raindrop-Removal-With-Light-Field-Image-Using-Image-Inpainting
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - scipy=1.2.1
  - opencv=4.5.1
  - torchvision
  - pyaml
  - scikit-image=0.17.1
  - jupyterlab
  - pillow
  - tensorflow=1.15.0
  - glog
  - easydict
  - matplotlib
  - google-cloud-vision
  - pip:
      - azure-cognitiveservices-vision-computervision
  - pylint

