name: Raindrop-Removal-With-Light-Field-Image-Using-Image-Inpainting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - scipy=1.2.1
  - opencv
  - torchvision
  - pyaml
  - scikit-image
  - jupyterlab
  - pillow
  - pylint
